#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-HTML-Strip
Version  : 2.10
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/K/KI/KILINRAX/HTML-Strip-2.10.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/K/KI/KILINRAX/HTML-Strip-2.10.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libh/libhtml-strip-perl/libhtml-strip-perl_2.10-1.debian.tar.xz
Summary  : 'Perl extension for stripping HTML markup from text.'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-HTML-Strip-lib
Requires: perl-HTML-Strip-license
Requires: perl-HTML-Strip-man
Requires: perl(Sub::Uplevel)
Requires: perl(Test::Exception)
BuildRequires : perl(Sub::Uplevel)
BuildRequires : perl(Test::Exception)

%description
HTML::Strip
===========
This module strips HTML-like markup from text.
It is written in XS, and thus about five times quicker than using
regular expressions for the same task.

%package lib
Summary: lib components for the perl-HTML-Strip package.
Group: Libraries
Requires: perl-HTML-Strip-license

%description lib
lib components for the perl-HTML-Strip package.


%package license
Summary: license components for the perl-HTML-Strip package.
Group: Default

%description license
license components for the perl-HTML-Strip package.


%package man
Summary: man components for the perl-HTML-Strip package.
Group: Default

%description man
man components for the perl-HTML-Strip package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n HTML-Strip-2.10
mkdir -p %{_topdir}/BUILD/HTML-Strip-2.10/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/HTML-Strip-2.10/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/perl-HTML-Strip
cp deblicense/copyright %{buildroot}/usr/share/doc/perl-HTML-Strip/deblicense_copyright
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/HTML/Strip.pm

%files lib
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/auto/HTML/Strip/Strip.so

%files license
%defattr(-,root,root,-)
/usr/share/doc/perl-HTML-Strip/deblicense_copyright

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/HTML::Strip.3
